### ISSUE TITLE
Too many connections at the sever side 

### ISSUE THREAD

**Issue by musriabhijit** [delight-im/Android-DDP#127] opened 2017-02-01 11:22 UTC
if i use mMeteor.connect(); in every actvity class then the connection is increasing at the server side is there any way to reuse the previous connection which we have established and if i don't use the mMeteor.connect() then in the particular actvity class  we are not able to subscribe and make a call

**Comment by musriabhijit** [comment] 2017-02-01 11:25
@ocram  please help in this regard

**Comment by ocram** [comment] 2017-02-01 14:20
Duplicate of https://github.com/delight-im/Android-DDP/issues/118

It's obvious that the connection count increases if you establish a new connection in every single `Activity`. You have to use the `MeteorSingleton` class instead to manage connections for you.

**Closed by ocram** 2017-02-01 14:20 UTC
Labels: duplicate
